// Code generated by hertz generator.

package DouyinApi

import (
	"github.com/1037group/dousheng/cmd/api/biz/mw"
	"github.com/cloudwego/hertz/pkg/app"
)

func Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentlistMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _comment_ctionMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _favoriteMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _favoritelistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _action0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favorite_ctionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messagechatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _action1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _message_ctionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishlistMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _action2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publish_ctionMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _action3Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relation_ctionMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _followMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationfollowlistMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _friendMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _relationfriendlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user0Mw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feed0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _list3Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationfollowerlistMw() []app.HandlerFunc {
	return []app.HandlerFunc{mw.JwtMiddleware.MiddlewareFunc()}
}

func _list4Mw() []app.HandlerFunc {
	// your code...
	return nil
}
