server_root:
	kitex --thrift-plugin validator -module github.com/1037group/dousheng idl/feed.thrift # execute in the project root directory
server_cmd:
	kitex --thrift-plugin validator -module github.com/1037group/dousheng -service feed -use github.com/1037group/dousheng/kitex_gen ../../idl/feed.thrift # execute in cmd/feed