// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	douyin_user "github.com/1037group/dousheng/kitex_gen/douyin_user"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

var userServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*douyin_user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{
		"UserLogin":    kitex.NewMethodInfo(userLoginHandler, newUserServiceUserLoginArgs, newUserServiceUserLoginResult, false),
		"UserRegister": kitex.NewMethodInfo(userRegisterHandler, newUserServiceUserRegisterArgs, newUserServiceUserRegisterResult, false),
		"User":         kitex.NewMethodInfo(userHandler, newUserServiceUserArgs, newUserServiceUserResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "douyin_user",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func userLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyin_user.UserServiceUserLoginArgs)
	realResult := result.(*douyin_user.UserServiceUserLoginResult)
	success, err := handler.(douyin_user.UserService).UserLogin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUserLoginArgs() interface{} {
	return douyin_user.NewUserServiceUserLoginArgs()
}

func newUserServiceUserLoginResult() interface{} {
	return douyin_user.NewUserServiceUserLoginResult()
}

func userRegisterHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyin_user.UserServiceUserRegisterArgs)
	realResult := result.(*douyin_user.UserServiceUserRegisterResult)
	success, err := handler.(douyin_user.UserService).UserRegister(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUserRegisterArgs() interface{} {
	return douyin_user.NewUserServiceUserRegisterArgs()
}

func newUserServiceUserRegisterResult() interface{} {
	return douyin_user.NewUserServiceUserRegisterResult()
}

func userHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*douyin_user.UserServiceUserArgs)
	realResult := result.(*douyin_user.UserServiceUserResult)
	success, err := handler.(douyin_user.UserService).User(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUserArgs() interface{} {
	return douyin_user.NewUserServiceUserArgs()
}

func newUserServiceUserResult() interface{} {
	return douyin_user.NewUserServiceUserResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UserLogin(ctx context.Context, req *douyin_user.UserLoginRequest) (r *douyin_user.UserLoginResponse, err error) {
	var _args douyin_user.UserServiceUserLoginArgs
	_args.Req = req
	var _result douyin_user.UserServiceUserLoginResult
	if err = p.c.Call(ctx, "UserLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserRegister(ctx context.Context, req *douyin_user.UserRegisterRequest) (r *douyin_user.UserRegisterResponse, err error) {
	var _args douyin_user.UserServiceUserRegisterArgs
	_args.Req = req
	var _result douyin_user.UserServiceUserRegisterResult
	if err = p.c.Call(ctx, "UserRegister", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) User(ctx context.Context, req *douyin_user.UserRequest) (r *douyin_user.UserResponse, err error) {
	var _args douyin_user.UserServiceUserArgs
	_args.Req = req
	var _result douyin_user.UserServiceUserResult
	if err = p.c.Call(ctx, "User", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
